import {
  LayoutGrid,
  Code2,
  Smartphone,
  Palette,
  Type,
  Search,
  Mail,
  Play,
  Zap,
  Settings,
  Server,
  Database,
  ShieldCheck,
  BarChart3,
  Megaphone,
  PenTool,
  Image,
  Video,
  Globe,
  ShoppingCart,
  CreditCard,
  Users,
  Calendar,
  FileText,
  Rocket,
  Sparkles,
  Layers,
  Monitor,
  Wrench,
  Camera,
  Send,
  Workflow,
  Check,
  type LucideIcon,
} from 'lucide-react'

/** Íconos disponibles para las características de un bloque. */
export const ICONOS: Record<string, LucideIcon> = {
  layout: LayoutGrid,
  code: Code2,
  mobile: Smartphone,
  palette: Palette,
  type: Type,
  search: Search,
  mail: Mail,
  play: Play,
  zap: Zap,
  settings: Settings,
  server: Server,
  database: Database,
  shield: ShieldCheck,
  chart: BarChart3,
  megaphone: Megaphone,
  pen: PenTool,
  image: Image,
  video: Video,
  globe: Globe,
  cart: ShoppingCart,
  card: CreditCard,
  users: Users,
  calendar: Calendar,
  file: FileText,
  rocket: Rocket,
  sparkles: Sparkles,
  layers: Layers,
  monitor: Monitor,
  wrench: Wrench,
  camera: Camera,
  send: Send,
  workflow: Workflow,
}

export const ICONOS_LISTA = Object.keys(ICONOS)

/** Devuelve el componente de ícono por nombre (fallback: check). */
export function getIcono(nombre?: string | null): LucideIcon {
  return (nombre && ICONOS[nombre]) || Check
}
